language: python
python: "3.7"
dist: xenial
os: linux

services:
  - docker

before_install:
  - sudo apt-get update
  - sudo apt-get -y install gcc-4.8
  - sudo apt-get -y install docker-ce

install:
  - python -m pip install --upgrade -r .requirements.lock --trusted-host pypi.python.org

addons:
  apt:
    packages:
      cmake

jobs:
  include:
    - stage: "Pylint: Run Linter"
      script: make lint

    - stage: "Pytest: Run test suite"
      script: make test
      after_success:
          - codecov

    - stage: "Docker: Build, Tag, Push"
      script:
        - docker login --username ${DOCKER_USERNAME} --password ${DOCKER_PASSWORD}
        - echo 'docker build -f ./Dockerfile -t ${TRAVIS_REPO_SLUG}:${TRAVIS_COMMIT}-travis-${TRAVIS_BUILD_NUMBER} .'
        - docker build -f ./Dockerfile -t ${TRAVIS_REPO_SLUG}:${TRAVIS_COMMIT}-travis-${TRAVIS_BUILD_NUMBER} .
      after_success:
        - docker push ${TRAVIS_REPO_SLUG}:${TRAVIS_COMMIT}-travis-${TRAVIS_BUILD_NUMBER}
