language: python
python:
  - "3.7"
dist:
  - xenial

services:
    - docker

before_install:
  - sudo apt-get update
  - sudo apt-get -y install gcc-4.8

install:
    - pip install --upgrade -r .requirements.lock --trusted-host pypi.python.org

addons:
  apt:
    packages:
      cmake

jobs:
    include:
      - stage: "Run test suite"
        script: make ci-test
        env:
          - WORKDIR=/home/travis/build/ralston3/kademlia
          - APPDIR=${WORKDIR}/kademlia

      # push image to repo
