language: python
python: "3.7"
dist: xenial
os: linux

services:
  - docker

before_install:
  - sudo apt-get update
  - sudo apt-get -y install gcc-4.8
  - sudo apt-get -y install docker-ce

install:
    - python -m pip install --upgrade -r .requirements.lock --trusted-host pypi.python.org

addons:
  apt:
    packages:
      cmake

jobs:
    include:
      - stage: "Pylint: Run Linter"
        script: make lint

      - stage: "Pytest: Run test suite"
        script: make test
        after_success:
            - codecov

      - stage: "Docker: Build, Tag, Push"
        script:
        - docker login --username $DOCKER_USERNAME --password $DOCKER_PASSWORD
        - export REPOSITORY=ralston3/liaa
        - docker build -f ./Dockerfile -t $REPOSITORY:$COMMIT-travis-$TRAVIS_BUILD_NUMBER .
        # on:
        #   all_branches: true
          # condition: ${TRAVIS_PULL_REQUEST_BRANCH:-$TRAVIS_BRANCH} =~ ^v(\d+)\.(\d+)\.(\d+)$
        after_success:
          - docker push $REPOSITORY:$COMMIT-travis-$TRAVIS_BUILD_NUMBER

    - stage: "Pypi: Push"
      script:
      - python -m twine upload -u $PYPI_USERNAME -p $PYPI_PASSWORD dist/*
      # on:
      #   all_branches: true
        # condition: ${TRAVIS_PULL_REQUEST_BRANCH:-$TRAVIS_BRANCH} =~ ^v(\d+)\.(\d+)\.(\d+)$
        
