language: python
python: "3.7"
dist: xenial
os: linux

before_install:
  - sudo apt-get update
  - sudo apt-get -y install gcc-4.8
  - sudo apt-get -y install docker-ce

install:
  python -m pip install --upgrade -r .requirements.lock --trusted-host pypi.python.org

addons:
  apt:
    packages:
      make cmake

jobs:
  include:
    - stage: "Pylint: Run Linter"
      script: make lint

    - stage: "Pytest: Run test suite"
      script: make test
      after_success:
          - codecov

    - stage: "Docker: Build, Tag, Push"
      if: branch =~ ^v
      script:
        - docker login --username ${DOCKER_USERNAME} --password ${DOCKER_PASSWORD}
        - docker build -f ./Dockerfile -t ${TRAVIS_REPO_SLUG}:${TRAVIS_BRANCH}-travis-${TRAVIS_BUILD_NUMBER} .
      after_success:
        - docker push ${TRAVIS_REPO_SLUG}:${TRAVIS_BRANCH}-travis-${TRAVIS_BUILD_NUMBER}

    - stage: "Docker: Build, Tag, Push (latest)"
      if: branch = master
      script:
        - docker login --username ${DOCKER_USERNAME} --password ${DOCKER_PASSWORD}
        - docker build -f ./Dockerfile -t ${TRAVIS_REPO_SLUG}:latest .
      after_success:
        - docker push ${TRAVIS_REPO_SLUG}:latest

    - stage: "PyPi: Push"
      if: branch = master
      script:
        - python setup.py sdist bdist_wheel
      after_success:
        - python -m twine upload --repository-url https://upload.pypi.org/legacy/ dist/* -u ${PYPI_USERNAME} -p ${PYPI_PASSWORD}
  