language: python
python:
  - "3.7"
dist:
  - xenial

services:
    - docker

before_install:
  - sudo apt-get update
  - sudo apt-get -y install gcc-4.8

install:
    - python -m pip install --upgrade -r .requirements.lock --trusted-host pypi.python.org

addons:
  apt:
    packages:
      cmake

jobs:
    include:
      - stage: "Run pylint"
        script: make lint
      - stage: "Build docker image and push"
        script: make branch="${TRAVIS_BRANCH}:${TRAVIS_BUILD_NUMBER}" dockerize
      - stage: "Run test suite"
        script: make test
        after_success:
            - codecov
