language: python
python:
  - "3.7"
dist:
  - xenial

services:
    - docker

before_install:
  - sudo apt-get update
  - sudo apt-get -y install gcc-4.8

install:
    - python -m pip install --upgrade -r .requirements.lock --trusted-host pypi.python.org

addons:
  apt:
    packages:
      cmake

jobs:
    include:
      - stage: "Run pylint"
        script: make lint
      - stage: "Run test suite"
        script: make test
        after_success:
            - codecov
after_success:
  - docker login -e $DOCKER_EMAIL -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
  - export REPOSITORY=ralston3/kademlia
  - docker build -f ./Dockerfile -t $REPOSITORY:$COMMIT .
  - docker tag $REPOSITORY:$COMMIT $REPOSITORY:$TRAVIS_BRANCH
  - docker tag $REPOSITORY:$COMMIT $REPOSITORY:travis-$TRAVIS_BUILD_NUMBER
  - docker push $REPOSITORY
